name: Update File Count
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
       python-version: 3.8
    - name: execute py script
      run: |
         pip install PyGithub==1.54.1 && 
         python main.py
      env:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
